<nav>
  <div class="titulo">
    <h1 class="primero">ENER<span class="segundo">GYM</span></h1>
  </div>
  <div class="menu">
    <!-- Agregar direcciones faltantes -->
    <ul>
      <li><a href="index.php">INICIO</a></li>
      <li><a href="dieta.php">DIETA</a></li>
      <li><a href="index.php">SOBRE NOSOTROS</a></li>
      <li><a href="#contact">CONTACTO</a></li>
      <li>
        <a href="login.php">INICIO DE SESION</a>
      </li>
      /
      <li><a href="registro.php">REGISTRARME</a></li>
    </ul>
  </div>
</nav>
