<footer id="contact">
  <div class="footer-container">
    <div class="footer-section">
      <h3>Sobre nosotros</h3>
      <p>&copy; 2023 ENERGYM.COM TODOS LOS DERECHOS RESERVADOS</p>
    </div>
    <div class="footer-section">
      <h3>Contactanos</h3>
      <ul>
        <li>Alajuela</li>
        <li>Orotina, Mastate 10201</li>
        <li>506 (61555619)</li>
        <li>contrerasaaron447@gmail.com</li>
      </ul>
    </div>
    <div class="footer-section">
      <h3>Siguenos</h3>
      <ul class="social">
        <li>
          <a href="" class="fa fa-facebook"></a>
        </li>
        <li>
          <a href="" class="fa fa-instagram"></a>
        </li>
        <li><a href="#" class="fa fa-twitter"></a></li>
        <li><a href="#" class="fa fa-linkedin"></a></li>
        <li><a href="#" class="fa fa-youtube"></a></li>
      </ul>
    </div>
  </div>
</footer>
